### ISSUE TITLE
Crash ved sidste par [BUG]

### ISSUE THREAD

**Issue by Gust2491** [orc13a/Sorteper-kortspil#2]
**Hvad fejlen gør**
Der er en fejl som gjorde at spillet crashede i nogle tilfælde når man tager det sidste kort fra den sidste modstander.

**Forventet resultat**
At den ikke crasher og giver navnet på taberen

**Styresystem**
Windows 10

**Error code**
ArrayIndexOutOfBoundsException: -1

under game-controller linje 46

**Comment by orc13a** [comment]
the bug has been fixed
